### PR TITLE
Add lisSourcedId field to Person, CourseOffering, CourseSection (cc204)

### PR DESCRIPTION
**Pull request by ViktorHaag**
Add LIS identifiers to fixtures per [caliper central #204](https://github.com/IMSGlobal/caliper-central/issues/204).

### CODE REVIEW

**Comment by ViktorHaag** [comment]
Note that this adds the LIS ID fields that get passed via LTI; it doesn't add other identifiers for things from other services (i.e. other LIS things or OneRoster things).

It also does not add LTI fields on EdApp, as I believe we need further consideration on whether those fields really belong on EdApp or perhaps on Session?

**Comment by ojurosevic** [comment]
Lets open a new issue that will accommodate for some type of universal ID that will help us to communicate the ID and source in more flexible way : #219

**Comment by ViktorHaag** [comment]
This is liable to not be what we want for [caliper-central #204](https://github.com/IMSGlobal/caliper-central/issues/204)... we'll want a more general and extensible solution instead. Closing this, and we can re-open a new PR when we have a design for that second approach.

**Comment by ViktorHaag** [comment]
Reviving this as "the simpler option" to see if we really want this, or a more general one.

**Pull request merged**
