### PR TITLE
fixture for multicontext

### PR DESCRIPTION
**Pull request by lsloan**
Fixture for testing multicontext handling in Kaltura's PR: IMSGlobal/caliper-php#326

### CODE REVIEW

**Comment by ViktorHaag** [comment]
I have concerns about this approach; I thought that because of our desire to let people support Caliper as much as possible without needing to know/use JSON-LD, we were restricting ourselves to extended `@context` definitions to only allow URIs to remote context documents that were in the IMS Caliper collection...

I'm concerned about requiring Caliper endpoints to be fully JSON-LD capable to make sense of data they receive.

**Comment by ViktorHaag** [comment]
Also, I'm not sure that this fixture really exercises what the intention is? The idea for a context array in actual use would be to use it to mixin vocabulary that doesn't exist in base Caliper, correct? Does this fixture actually test that?

This whole "extended vocabulary via use of JSON-LD" frankly makes me really nervous and we need to have some hard thoughts about how we're going to support that in certification...

... I'm really starting to lean back towards thinking that we have a hard requirement to let Sensors and Endpoints _not_ support JSON-LD, and that Caliper certification be firmly based on that, without allowing for JSON-LD extension, and requiring use of JSON-schema _only_ to validate payloads.

This doesn't mean that implementations in the field couldn't use JSON-LD features to extend Caliper, but I'm not sure we should allow any of that near _the specification_ and certification requirements.

**Comment by ViktorHaag** [comment]
Hey @arwhyte and @lsloan -- we should probably talk about this on a call (or at LILI), or close this?

**Comment by arwhyte** [comment]
@lsloan -- can you change your PR to use this example (it works in the jsonld.org playground):

```
{
	"@context": ["https://schema.org/docs/jsonldcontext.json", "http://purl.imsglobal.org/ctx/caliper/v1p1"],
	"id": "urn:uuid:3a648e68-f00d-4c08-aa59-8738e1884f2c",
	"type": "Event",
	"profile": "GeneralProfile",
	"actor": {
		"id": "https://example.edu/users/554433",
		"type": "Person"
	},
	"action": "Submitted",
	"object": {
		"id": "https://example.edu/handle/2027.42/130810",
		"type": "Thesis",
		"author": {
			"id": "https://example.edu/users/554433",
			"type": "Person"
		},
		"name": "A Dissertation.",
		"inSupportOf": "Doctor of Philosophy",
		"sourceOrganization": {
			"id": "https://example.edu/",
			"type": "Organization"
		}
	},
	"eventTime": "2018-11-15T10:15:00.000Z"
}
```

**Comment by ViktorHaag** [comment]
The form of this fixture especially concerns me with respect to _certification_. Is this fixture certified-to-be-good Caliper? I'm not sure... we need to have a stance on this, @arwhyte and @bracken.

If we decide that this _is_ valid Caliper, how do we test it in cert? (Like, there's a difference between this being possible, and this being approved in the cert process...)

**Comment by lsloan** [comment]
My apologies for the extra commits.  I didn't notice until after the first commit was done that it wasn't signed.  I was certain I had signing enabled by default.

@ViktorHaag, I agree about comments in JSON.  I believe there may be new versions of JSON proposed that allow comments.  OTOH, YAML allows comments *and* it can contain JSON.  So… let's change all of Caliper to use YAML instead!  😉

@arwhyte, I've added your suggested fixture under a new filename that reflects its content.  The intention of the fixture I'd originally committed was to test Kaltura's use of a nonstandard action with the MediaEvent.  If we don't need to test that specific scenario, should I remove `v1p1/caliperEventMediaPausedVideoMultiContext.json` from this PR?

**Comment by ViktorHaag** [comment]
> @ViktorHaag, I agree about comments in JSON. I believe there may be new versions of JSON proposed that allow comments (e.g., https://json5.org/). OTOH, YAML allows comments _and_ it can contain JSON. So… let's change all of Caliper to use YAML instead! 😉

Hmm, that's not an unreasonable suggestion -- at least we could have _all the fixtures_ written in YAML, so that we can have _fixture metadata_ (including comments) that would be quite useful _as well_ as the JSON of the actual serialized example(s) that comprise the test fixture itself.

With this approach we could:
- have comments in the fixtures
- have meta-data that could hint/configure the _way_ in which the fixture could be used in test/docs
- bundle together several fixtures in logical ways without using the Envelop bundling mechanism that's part of Caliper itself, and so better organize our fixtures, and reduce the sheer number of files we have

I think this is maybe such a good idea, we should probably have an issue for it in c-central as a backlog item for us to work with later.

**Comment by arwhyte** [comment]
I'm going to merge this PR so that I can transfer the develop branch to caliper spec.  After that, we need to do the following:
1) fix Lance's fixture so that the faux context is made a real context
2) perhaps change my fixture so that the object of the interaction is a Caliper entity (not a schema.org entity) and add schema.org terms as extensions.

**Pull request merged**
