### PR TITLE
entities for Aggregate Measures expansion to Tool Use profile

### PR DESCRIPTION
**Pull request by ViktorHaag**
AggregateMeasure entities from the expanded Tool Use (aggregate measures) proposal (see https://github.com/IMSGlobal/caliper-central/issues/202). Once we get these fixtures in good shape, we should make sure to circle back and update the spec's examples to match.

I will follow up in another commit to include a new ToolUse Event as well.

*Note* -- these are not final, and are meant to be discussed; I add them here so we have something to refer to in discussion. For example, I have not included any `display` text properties for these, pending the outcome of that discussion to be had in the working group.

### CODE REVIEW

**Comment by dccarroll** [comment]
looks good to me!

**Comment by arwhyte** [comment]
As I mentioned in another comment one can add the existing `Entity.name` property to `AggregateProgresss` if there is a need to further decorate the entity with a local descriptor, as in:

```
{
            "id": "urn:uuid:ade6070b-02e1-4da6-a18f-55ce70d547a0",
            "type": "AggregateProgress",
            "name": "Exercises completed"
            "value": 12.0,
            "valueMax": 25.0,
            "metric": "UnitsCompleted",
            "startedAtTime": "2018-08-15T10:15:00.000Z",
            "endedAtTime": "2018-11-15T10:15:00.000Z"
        }
```

**Comment by arwhyte** [comment]
Once merged, I will update the draft ToolUse Profile doc example JSON-LD. :)

**Comment by ViktorHaag** [comment]
(Hey @arwhyte)  Relevant date-times have been updated for 2019. I _only touched net-new timestamps here_. I have not updated timestamps for user, membership, and so on, because those are standard entities that exist in other places.

If this is a concern for us, we maybe should have a PR against all the v1p1 (and v1p2) fixtures that rolls forward all dates to 2019.

**Comment by arwhyte** [comment]
For this `Event` I recommend updating all `DateTime` values to 2019.  I doesn't make sense temporally for the `Membership` of a current course to be dated back to 2016; same is true for `Session`.

I suggest that for the new events/entities fixtures or existing events/entities fixtures that are modified, that we update all the year component of the `DateTime` values to the year in which we anticipate that the document will be published. 

Thinking about the v1p2 spec it would be "nice" if we could refresh all the `DateTime` values for the v1p2 fixtures if the working group has no objections.  I think refreshed example JSON-LD would make the doc look truly refreshed -- but it's a nice-to-have.

**Comment by ViktorHaag** [comment]
In order to put new, different timestamps on the entities that are shared across fixtures, we'd need to generate new identifiers for them, at least, and probably new other data as well (for example, the course offering entity has clear indication in its URL that it's a '2016' thing), because if we change one part of them they're no longer "the same".

I get what you'd like to do here, but I suspect the easiest way to keep dates "relevant" is to sort of treat the dates in fixtures like copyright dates.

When you roll into a new year, if a fixture directory is still being "used", you batch-roll _all_ dates forward one calendar year.

The downside to this is you'd probably want to do a one-time pass that would verify that all the internal date windows for the things in the fixture directory "make sense" (i.e. you don't have spans crossing a year boundary over Jan1).

The upside is you could then do this once as a cleanup item, and not have to worry about this weird problem more than once a year.

I'm afraid that if we don't keep regular consistency like this of the Caliper things used in more than one place within the fixtures, we might cause someone's test code to break (because they might be, for some reason, looking to treat fixtures with the same @id as the same node and have tests that are fragile around that point).

Having a "once a year make an update PR to roll the dates forward" also makes dealing with this simple, and not something we have to continually manage...

**Comment by arwhyte** [comment]
> for example, the course offering entity has clear indication in its URL that it's a '2016' thing

Yes, I already do that.  Should have noted it in detail.

**Comment by ViktorHaag** [comment]
In the interests of getting things moving and separating concerns, @arwhyte, I would like to propose that we accept and merge this PR to get the aggregate measure fixtures into the test base so they can be used, and then issue a second, lower-priority PR against the entire fixtures directory that would address the date issue -- I think that's a cleanup concern and a lower priority.

Are you OK with that?

**Comment by arwhyte** [comment]
@ViktorHaag -- ok with me.  Merging now.

**Comment by ViktorHaag** [comment]
Thanks, Anthony.

**Pull request merged**
